### ISSUE TITLE
Fieldtype Grid

### ISSUE THREAD

**Issue by bognarl** [aryehdesigns/statamic-fetch#4]
Hi. I just realized that if I use Grid type field in my collection Fetch only returns the last item of the array because of the `$array->collapse()` in `Fetch.php:47`.

**This is what it looks like in the md:**
```
output_fields:
  - 
    name: Some name
    cell: G2
  - 
    name: Some other name
    cell: H2
  - 
    name: Some other other name
    cell: I2
```

**And this is what Fetch returns:**
```
  "output_fields": {
    "name": "Some other other name",
    "cell": "I2"
  },
```

Do you have any idea on how to prevent this? I don't want to remove `$array->collapse()` as it is really useful on other fields.
